panes:
  - command: <agent> # Start the configured agent (e.g., claude)
    focus: true
  - split: horizontal # Second pane with default shell

# Commands run after worktree creation (blocks window creation, keep fast)
post_create:
  - python -m venv tests/venv
  - source tests/venv/bin/activate && pip install --disable-pip-version-check -r tests/requirements.txt

files:
  symlink:
    - CLAUDE.md
    - target # Share Rust build cache for faster compilation
