panes:
  - command: <agent> # Start the configured agent (e.g., claude)
    focus: true
  - split: horizontal # Second pane with default shell

# Commands run after worktree creation (blocks window creation, keep fast)
post_create:
  - direnv allow # Allow direnv to activate mise for this worktree

files:
  copy:
    - .envrc # Copy direnv config (might need per-worktree customization)
  symlink:
    - CLAUDE.md
    - tests/venv # Share Python venv for faster worktree creation
    - .ignore
    - history

pre_merge:
  - just check
  - just test
